### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by briochemc** [briochemc/GEOTRACES.jl#2]
- [ ] Deal with uncertainty on a transect or profile/station basis, by taking the maximum of the available std, the minimum observed diff, the last significant digit?
- [ ] plotting recipes mimicing Ocean Data View
- [x] figure out a way to CI despite the GEOTRACES data-access restrictions
- [ ] Fix standard deivation code
